AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample functions for MCP servers.

Resources:

  CustomerInfoFromId:
    Type: AWS::Serverless::Function
    #checkov:skip=CKV_AWS_115:Because this is an example, there is no requirement to reserve concurrency
    #checkov:skip=CKV_AWS_116:Because this is an example, there is no requirement for a DLQ
    #checkov:skip=CKV_AWS_117:Because this is an example, there is no requirement to run within a VPC
    Properties:
      CodeUri: ./customer-info-from-id
      Description: Customer status from { 'customerId' }
      MemorySize: 128
      Timeout: 3
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - arm64

  CustomerIdFromEmail:
    Type: AWS::Serverless::Function
    #checkov:skip=CKV_AWS_115:Because this is an example, there is no requirement to reserve concurrency
    #checkov:skip=CKV_AWS_116:Because this is an example, there is no requirement for a DLQ
    #checkov:skip=CKV_AWS_117:Because this is an example, there is no requirement to run within a VPC
    Properties:
      CodeUri: ./customer-id-from-email
      Description: Get customer ID from { 'email' }
      MemorySize: 128
      Timeout: 3
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - arm64

Outputs:

  CustomerInfoFromId:
    Description: "CustomerInfoFromId Function ARN"
    Value: Fn::GetAtt CustomerInfoFromId.Arn

  CustomerIdFromEmail:
    Description: "CustomerIdFromEmail Function ARN"
    Value: Fn::GetAtt CustomerIdFromEmail.Arn
